language: php

php:
  - 7.0

env:
  APP_ENV: testing
  CACHE_DRIVER: redis
  SESSION_DRIVER: redis
  QUEUE_DRIVER: sync
  DB_CONNECTION: sqlite
  APP_KEY: 16efa6c23c2e8c705826b0e66778fbe7

branches:
  - master

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8.7.0
  - nvm use 8.7.0
  - npm i
  - composer self-update
  - composer install --prefer-dist --no-interaction

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - redis-server

before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update

script:
  - vendor/bin/phpunit
  - npm test